apiVersion: v1
kind: Pod
metadata:
  name: mig-test-pod
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:11.8.0-base-ubuntu22.04
    command: ["sleep", "3600"]
    resources:
      limits:
        nvidia.com/mig-1g.10gb: 1

