apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: gpu-claim-template
spec:
  spec:
    devices:
      requests:
        - name: my-gpu
          deviceClassName: gpu.nvidia.com
          allocationMode: ExactCount
          count: 1

